name: Dev
on: 
  push:
    branches: [ dev ]

jobs:
  build_romfs_dev:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      
      - name: checkout version
        uses: actions/checkout@v2
      # build the zip
      - name: build distribution
        shell: bash
        run: |
          ls && cd scripts && python3 make_dist.py && cd ..
          mv build.zip romfs.zip
      # - name: Delete ROMFS Build
      #   uses: dev-drprasad/delete-tag-and-release@v0.2.0
      #   with:
      #     repo: WuBoytH/WuBor-Romfs
      #     delete_release: true
      #     tag_name: dev
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      # upload asset
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_name: WuBoytH/WuBor-Romfs
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: 'romfs*.zip'
          prerelease: true
          file_glob: true
          asset_name: the_asset
          release_name: dev
          tag: dev
          overwrite: true
          body: "This is a ROMFS build with all of the latest files for a WuBor Patch Dev build."