name: Dev
on: 
  push:
    branches-ignore:
      - "main"
      - "dev"

jobs:
  build_romfs_dev:
    env:
      PLUGIN_NAME: the_wubor_patch
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      
      - name: checkout version
        uses: actions/checkout@v2
      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6
      # build the zip
      - name: build distribution
        shell: bash
        run: |
          ls && cd scripts && python3 make_dist.py && cd ..
          mv build.zip romfs.zip
      ## mock upload files
      #- run: |
      #    mkdir distributions
      #    echo lol > distributions/hdr-switch.zip
      #    echo lol > distributions/hdr-ryujinx.zip

      # upload asset
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: WuBoytH/WuBor-Romfs
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: 'romfs*.zip'
          prerelease: true
          file_glob: true
          asset_name: the_asset
          release_name: ${{ steps.branch-name.outputs.current_branch }}
          tag: ${{ steps.branch-name.outputs.current_branch }}
          overwrite: true